name: Download Latest Release Assets

on:
  push:
    branches:
      - main
  

jobs:
  download-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/gh-cli@v1

      - name: Get latest release data
        id: get_latest_release
        run: |
          latest_release=$(gh release view --repo coder/code-server --json assets --jq '.assets[] | select(.name | endswith("amd64.tar.gz")).url')
          echo "release_url=${latest_release}" >> $GITHUB_ENV

      - name: Download amd64.tar.gz
        run: |
          curl -L ${{ env.release_url }} -o code-server-amd64.tar.gz

      - name: Verify file
        run: |
          ls -lh code-server-amd64.tar.gz
          
      - name: Move assets to current directory
        run: |
          mv code-server-amd64.tar.gz ./
      
      - name: Configure Git
        run: |
          git config --global user.email "theangkko@gmail.com"
          git config --global user.name "theangkko"
     
          
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add downloaded assets"
          git push origin main
